#### globlal
# no_lst = [
#     '29323af8', '4775e433', 'a9afc5b5', '0c3472e0', '119ee881', '39d813ad', 'd21fac6b', '60233c58', '0fe890cf',
#     '60233c58',
#     'b4b518a6', '2da11096', '0a148684', '4b7f1a58', 'a32ef104', 'f4735eab', '58913c17', 'd32a66f1', '6b326045',
#     '1e560a97',
#     '21a01148', '536a3059', '2fbb782e', 'd77cb2e6', '5f032538', 'f8de451a', '5452c0e6', '5d7a57b6', '7d8d817f',
#     # dbc56d3f
#     '3236584a', 'b36999c8', '09a1d049', '007c5ad0', '3b2e8ae1', '17b91631', 'a9f81feb'
# ]

dict_columns = {
    '기기일련번호': 'sid',
    '검사번호': 'tid',
    '환자 나이(만)': 'age_group',
    '병원구분': 'hosp_type',
    '처방병원명': 'hosp_name',
    '처방 교수님 성명': 'doct_name',
    '상품종류': 'prod_type',
    '상품내역': 'prod_detail',
    '처방일수': 'prsc_days',
    '처방구간': 'prsc_period',
    '검사시작': 'prsc_start_at',
    '처방년도': 'prsc_year',
    '처방월단위': 'prsc_mon',
    '처방월': 'prsc_month',
    '처방주': 'prsc_week',
    '처방일': 'prsc_date',
    '처방요일': 'prsc_day',

    '처방_리드오프_리드타임': 'prsc_ldff_leadtime',
    '리드오프시점': 'ldff_at',
    '리드오프년도': 'ldff_year',
    '리드오프월단위': 'ldff_mon',
    '리드오프월': 'ldff_month',
    '리드오프주': 'ldff_week',
    '리드오프일': 'ldff_date',
    '리드오프요일': 'ldff_day',
    '리드오프_업로드_리드타임': 'ldff_upld_leadtime',

    '처방기준 종료시점': 'prsc_end_at',
    '처방종료일': 'prsc_end_date',
    '처방종료월단위': 'prsc_end_mon',
    '처방종료월': 'prsc_end_month',
    '처방종료주': 'prsc_end_week',
    '처방종료년도': 'prsc_end_year',
    '처방종료요일': 'prsc_end_day',

    '업로드아이디': 'upld_id',
    '데이터업로드': 'upld_at',
    '업로드년도': 'upld_year',
    '업로드월단위': 'upld_mon',
    '업로드월': 'upld_month',
    '업로드주': 'upld_week',
    '업로드일': 'upld_date',
    '업로드요일': 'upld_day',
    'RECORDING': 'record_duration',
    'record_expt': 'record_expt',
    'record_real': 'record_real',

    '업로드_분석_리드타임': 'upld_rept_leadtime',
    '레포트아이디': 'rept_id',
    '병원 레포트 제공 시점': 'rept_at',
    '레포트제공년도': 'rept_year',
    '레포트제공월단위': 'rept_mon',
    '레포트제공월': 'rept_month',
    '레포트제공주': 'rept_week',
    '레포트제공일': 'rept_date',
    '레포트제공요일': 'rept_day',
}
